"""
 
Module Name: bigquery_connector.py
 
Description:
This module provides functionality to execute SQL queries on a Google BigQuery database.
It handles the connection setup using environment variables, execution of SQL queries,
and returning results in JSON format. Errors are handled and returned as JSON strings
to ensure robustness.
 
Note:
    - This uses a single dataset name for all queries.
    - The dataset name is fetched from the .env file.
 
"""
 
# -----------------------------------------------------------------------------
# SECTION: Imports
# -----------------------------------------------------------------------------
 
# Standard library imports
from typing import Dict, Any
import json
import os
import re
import datetime
 
# Third-party imports
from dotenv import load_dotenv
from google.cloud import bigquery
from google.api_core import exceptions as gcloud_exceptions
from google.oauth2 import service_account
 
# -----------------------------------------------------------------------------
# SECTION: Environment Variable Loading
# -----------------------------------------------------------------------------
 
# Load environment variables from the .env file
load_dotenv()
 
# Retrieve environment variables
GCP_CREDENTIALS_PATH = os.getenv("GCP_CREDENTIALS_PATH")  # Path to your service account JSON file
BQ_PROJECT_ID = "bcone-sales-insights-dev-prj"  # Google Cloud Project ID
BQ_DATASET = "bcone-sales-insights-dev-bqd" # Default dataset for queries
 
# -----------------------------------------------------------------------------
# SECTION: Clean unwanted Double Quotes from LLM-Generated SQL Queries
# -----------------------------------------------------------------------------
 
def clean_bigquery_query(query: str) -> str:
    """
    Cleans unwanted double quotes from an LLM-generated SQL query while keeping
    double quotes around identifiers with special characters.
    Args:
        query (str): The SQL query generated by the LLM.
    Returns:
        str: The cleaned and executable SQL query.
    """
    # Step 1: Remove double quotes around standard identifiers but retain them for those with special characters
    cleaned_query = re.sub(r'\"([a-zA-Z0-9_]+)\"', r'\1', query)
    # Step 2: Replace multiple spaces/newlines with a single space
    cleaned_query = re.sub(r'\s+', ' ', cleaned_query)
    # Step 3: Trim leading and trailing spaces
    cleaned_query = cleaned_query.strip()
    return cleaned_query
 
# -----------------------------------------------------------------------------
# SECTION: Helper for JSON Serialization
# -----------------------------------------------------------------------------
 
def serialize_row(row: dict) -> dict:
    """
    Converts date and datetime objects in a row to ISO format strings for JSON serialization.
    """
    return {
        k: (v.isoformat() if isinstance(v, (datetime.date, datetime.datetime)) else v)
        for k, v in row.items()
    }
 
# -----------------------------------------------------------------------------
# SECTION: Executing SQL query on BigQuery
# -----------------------------------------------------------------------------
 
def execute_bigquery_query(sql_query: str) -> str:
    """
    Executes a SQL query on Google BigQuery and returns the result as a JSON string.
    """
    credentials = service_account.Credentials.from_service_account_file(GCP_CREDENTIALS_PATH)
    client = bigquery.Client(credentials=credentials)
 
    try:
        cleaned_query = clean_bigquery_query(sql_query)
 
        # ✅ Fix: Ensure correct dataset reference without duplication
        if not re.search(r'`[\w-]+\.[\w-]+\.[\w-]+`', cleaned_query):
            cleaned_query = re.sub(
                r'FROM\s+([\w_]+)',
                f'FROM `.\\1`',
                cleaned_query,
                flags=re.IGNORECASE
            )
        print("clean", cleaned_query)
        print(f"Query length: {len(cleaned_query)} characters")
       
        # Check if query looks incomplete (common indicators)
        if not cleaned_query.strip().endswith((';', ')', 'BY', 'ORDER', 'LIMIT', 'HAVING')):
            if cleaned_query.count('(') != cleaned_query.count(')'):
                print("WARNING: Unmatched parentheses detected")
            if not any(keyword in cleaned_query.upper() for keyword in ['SELECT', 'WITH']):
                print("WARNING: No SELECT or WITH clause found")
       
        # Check for common alias issues
        alias_references = re.findall(r'\b([a-z])\.[a-zA-Z_]', cleaned_query)
        for alias in set(alias_references):
            # Check if alias is defined
            alias_pattern = rf'(FROM|JOIN)\s+\w+\s+{alias}\b'
            if not re.search(alias_pattern, cleaned_query, re.IGNORECASE):
                print(f"WARNING: Reference to alias '{alias}' found but '{alias}' alias not defined")
               
                # Try to fix common patterns
                if alias == 't' and 'total_' in cleaned_query:
                    cleaned_query = re.sub(r'(CROSS JOIN|JOIN)\s+(total_\w+)(\s|$)', rf'\1 \2 {alias}\3', cleaned_query)
                    print(f"FIXED: Added missing alias '{alias}' to total table")
                elif alias == 's' and 'stage_' in cleaned_query:
                    cleaned_query = re.sub(r'(FROM|JOIN)\s+(stage_\w+)(\s|$)', rf'\1 \2 {alias}\3', cleaned_query)
                    print(f"FIXED: Added missing alias '{alias}' to stage table")
               
                print("Fixed query:", cleaned_query)
       
        # Execute the query
        query_job = client.query(cleaned_query)
        results = query_job.result()
 
        # Fetch column names
        column_names = [field.name for field in results.schema]
 
        # Convert results to JSON, handling date/datetime serialization
        rows = [serialize_row({column: row[column] for column in column_names}) for row in results]
 
        # Check for empty result
        if not rows:
            return json.dumps({
                "status": "no_data",
                "message": "No data available for the requested period.",
                "data": []
            })
        else:
            return json.dumps({
                "status": "success",
                "data": rows
            })
 
    except gcloud_exceptions.BadRequest as e:
        # BigQuery returns BadRequest for SQL syntax/validation errors (e.g., invalidQuery)
        return json.dumps({
            "error": "Something went wrong while processing your request. Please try rephrasing your question."
        })
    except Exception as e:
        # Preserve other error details for upstream handling (will be normalized by higher layers if needed)
        return json.dumps({
            "error": str(e)
        })