-- PostgreSQL Schema for Bristlecone AI Operations Assistant Backend
 
-- Users Table: Stores user login information.
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,                     -- Auto-incrementing unique identifier for the user
    email VARCHAR(255) UNIQUE NOT NULL,       -- User's email address (must be unique)
    password VARCHAR(255) NOT NULL,           -- User's password (ensure this is hashed in production!)
    first_name VARCHAR(100),                   -- User's first name
    last_name VARCHAR(100),                     -- User's last name
);
 
-- Chat Sessions Table: Stores metadata for each chat session.
CREATE TABLE IF NOT EXISTS chat_sessions (
    chat_id UUID PRIMARY KEY,                  -- Unique identifier for the chat session (UUID)
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- Foreign key referencing the users table (cascade delete)
    title VARCHAR(100) NOT NULL DEFAULT 'Untitled Chat', -- Title of the chat session
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP -- Timestamp when the chat session was created
);
 
-- Chat History Table: Stores individual messages within chat sessions.
CREATE TABLE IF NOT EXISTS chat_history (
    message_id SERIAL PRIMARY KEY,            -- Auto-incrementing unique identifier for the message
    chat_id UUID NOT NULL REFERENCES chat_sessions(chat_id) ON DELETE CASCADE, -- Foreign key referencing chat_sessions (cascade delete)
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- Foreign key referencing users (cascade delete) (can be useful for direct queries)
    question TEXT NOT NULL,                   -- The user's question/input
    response TEXT,                            -- The AI's text response (optional)
    response_graph JSONB,                     -- Graph data associated with the response (stored as JSONB) (optional)
    graph_type VARCHAR(50),                   -- Type of graph (e.g., 'line', 'bar', 'pie') (optional)
    insightful_questions TEXT,                -- Follow-up or insightful questions generated by the AI (optional)
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP -- Timestamp when the message was recorded
);
 
-- Optional: Add indexes for faster lookups, e.g., on user_id in chat_sessions
-- CREATE INDEX IF NOT EXISTS idx_chat_sessions_user_id ON chat_sessions(user_id);
-- CREATE INDEX IF NOT EXISTS idx_chat_history_new_chat_id ON chat_history_new(chat_id);
-- CREATE INDEX IF NOT EXISTS idx_chat_history_new_user_id ON chat_history_new(user_id);
 
-- Note: Ensure the database user running the backend application has the necessary
-- privileges (SELECT, INSERT, UPDATE, DELETE) on these tables.